// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const addTaskToProject = `-- name: AddTaskToProject :exec
WITH new_project_task AS (
    INSERT INTO project_tasks (task_id, project_id)
        VALUES ($1, $2)
        RETURNING task_id, project_id
)
INSERT INTO users_tasks (user_id, task_id)
SELECT $3, task_id FROM new_project_task
`

type AddTaskToProjectParams struct {
	TaskID    int64
	ProjectID int64
	UserID    int64
}

func (q *Queries) AddTaskToProject(ctx context.Context, arg AddTaskToProjectParams) error {
	_, err := q.db.ExecContext(ctx, addTaskToProject, arg.TaskID, arg.ProjectID, arg.UserID)
	return err
}

const createNewTaskStatus = `-- name: CreateNewTaskStatus :one
INSERT INTO task_status_types (owner_project_id, type)
VALUES ($1, $2)
RETURNING task_status_types_id, owner_project_id, type
`

type CreateNewTaskStatusParams struct {
	OwnerProjectID int64
	Type           string
}

func (q *Queries) CreateNewTaskStatus(ctx context.Context, arg CreateNewTaskStatusParams) (TaskStatusType, error) {
	row := q.db.QueryRowContext(ctx, createNewTaskStatus, arg.OwnerProjectID, arg.Type)
	var i TaskStatusType
	err := row.Scan(&i.TaskStatusTypesID, &i.OwnerProjectID, &i.Type)
	return i, err
}

const createProject = `-- name: CreateProject :one
WITH new_project AS (
    INSERT INTO projects (title, description, author_name, created_at)
        VALUES ($1, $2, $3, $4)
        RETURNING project_id, title, description, author_name, created_at)
INSERT
INTO users_projects (user_id, project_id)
SELECT $5, project_id
FROM new_project
RETURNING user_id, project_id
`

type CreateProjectParams struct {
	Title       string
	Description sql.NullString
	AuthorName  string
	CreatedAt   sql.NullTime
	UserID      int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (UsersProject, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Title,
		arg.Description,
		arg.AuthorName,
		arg.CreatedAt,
		arg.UserID,
	)
	var i UsersProject
	err := row.Scan(&i.UserID, &i.ProjectID)
	return i, err
}

const createTask = `-- name: CreateTask :one
WITH new_task AS (
    INSERT INTO tasks (title, description, priority, author_name, created_at, deadline)
        VALUES ($1, $2, $3, $4, $5, $6)
        RETURNING task_id, title, description, priority, author_name, created_at, deadline),
new_project_task AS (
    INSERT INTO project_tasks (task_id, project_id)
    SELECT task_id, $7 FROM new_task
    RETURNING task_id, project_id
)
INSERT
INTO users_tasks (user_id, task_id)
SELECT $8, task_id
FROM new_task
RETURNING user_id, task_id
`

type CreateTaskParams struct {
	Title       string
	Description sql.NullString
	Priority    TaskPriority
	AuthorName  string
	CreatedAt   sql.NullTime
	Deadline    sql.NullTime
	ProjectID   int64
	UserID      int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (UsersTask, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AuthorName,
		arg.CreatedAt,
		arg.Deadline,
		arg.ProjectID,
		arg.UserID,
	)
	var i UsersTask
	err := row.Scan(&i.UserID, &i.TaskID)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE
FROM tasks
WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, taskID)
	return err
}

const getAllTaskStatuses = `-- name: GetAllTaskStatuses :many
SELECT task_status_types_id, owner_project_id, type
FROM task_status_types
`

func (q *Queries) GetAllTaskStatuses(ctx context.Context) ([]TaskStatusType, error) {
	rows, err := q.db.QueryContext(ctx, getAllTaskStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStatusType
	for rows.Next() {
		var i TaskStatusType
		if err := rows.Scan(&i.TaskStatusTypesID, &i.OwnerProjectID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT task_id, title, description, priority, author_name, created_at, deadline
FROM tasks
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.AuthorName,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskById = `-- name: GetTaskById :one
SELECT task_id, title, description, priority, author_name, created_at, deadline
FROM tasks
WHERE task_id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, taskID int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskById, taskID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.AuthorName,
		&i.CreatedAt,
		&i.Deadline,
	)
	return i, err
}

const getTaskStatusByTaskId = `-- name: GetTaskStatusByTaskId :one
SELECT t.type
FROM task_statuses AS ts
         JOIN task_status_types AS t ON ts.task_status_id = t.task_status_types_id
WHERE ts.task_id = $1
`

func (q *Queries) GetTaskStatusByTaskId(ctx context.Context, taskID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskStatusByTaskId, taskID)
	var type_ string
	err := row.Scan(&type_)
	return type_, err
}

const getTasksByAuthor = `-- name: GetTasksByAuthor :many
SELECT task_id, title, description, priority, author_name, created_at, deadline
FROM tasks
WHERE author_name = $1
`

func (q *Queries) GetTasksByAuthor(ctx context.Context, authorName string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByAuthor, authorName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.AuthorName,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByDeadline = `-- name: GetTasksByDeadline :many
SELECT task_id, title, description, priority, author_name, created_at, deadline
FROM tasks
WHERE deadline <= $1
`

func (q *Queries) GetTasksByDeadline(ctx context.Context, deadline sql.NullTime) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByDeadline, deadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.AuthorName,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByPriority = `-- name: GetTasksByPriority :many
SELECT task_id, title, description, priority, author_name, created_at, deadline
FROM tasks
WHERE priority = $1
`

func (q *Queries) GetTasksByPriority(ctx context.Context, priority TaskPriority) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByPriority, priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.AuthorName,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByProject = `-- name: GetTasksByProject :many
SELECT t.task_id, t.title, t.description, t.priority, t.author_name, t.created_at, t.deadline
FROM tasks AS t
         JOIN project_tasks AS pt ON t.task_id = pt.task_id
WHERE pt.project_id = $1
`

func (q *Queries) GetTasksByProject(ctx context.Context, projectID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.AuthorName,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByStatus = `-- name: GetTasksByStatus :many
SELECT t.task_id, t.title, t.description, t.priority, t.author_name, t.created_at, t.deadline
FROM tasks AS t
         JOIN task_statuses AS ts ON t.task_id = ts.task_id
         JOIN task_status_types AS tst ON ts.task_status_id = tst.task_status_types_id
WHERE tst.type = $1
`

func (q *Queries) GetTasksByStatus(ctx context.Context, type_ string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByStatus, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.AuthorName,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskDeadline = `-- name: SetTaskDeadline :exec
UPDATE tasks
SET deadline = $2
WHERE task_id = $1
`

type SetTaskDeadlineParams struct {
	TaskID   int64
	Deadline sql.NullTime
}

func (q *Queries) SetTaskDeadline(ctx context.Context, arg SetTaskDeadlineParams) error {
	_, err := q.db.ExecContext(ctx, setTaskDeadline, arg.TaskID, arg.Deadline)
	return err
}

const setTaskStatus = `-- name: SetTaskStatus :exec
UPDATE task_statuses ts
SET task_status_id = (SELECT tst.task_status_types_id
                      FROM task_status_types tst
                      WHERE tst.type = $2
                        AND tst.owner_project_id = (SELECT pt.project_id
                                                    FROM project_tasks pt
                                                    WHERE pt.task_id = $1))
WHERE ts.task_id = $1
`

type SetTaskStatusParams struct {
	TaskID int64
	Type   string
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, setTaskStatus, arg.TaskID, arg.Type)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET title       = $2,
    description = $3,
    priority    = $4,
    author_name = $5,
    created_at  = $6,
    deadline    = $7
WHERE task_id = $1
`

type UpdateTaskParams struct {
	TaskID      int64
	Title       string
	Description sql.NullString
	Priority    TaskPriority
	AuthorName  string
	CreatedAt   sql.NullTime
	Deadline    sql.NullTime
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AuthorName,
		arg.CreatedAt,
		arg.Deadline,
	)
	return err
}
