// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const addTaskToProject = `-- name: AddTaskToProject :exec
INSERT INTO project_tasks (task_id, project_id)
VALUES ($1, $2)
`

type AddTaskToProjectParams struct {
	TaskID    string
	ProjectID string
}

func (q *Queries) AddTaskToProject(ctx context.Context, arg AddTaskToProjectParams) error {
	_, err := q.db.ExecContext(ctx, addTaskToProject, arg.TaskID, arg.ProjectID)
	return err
}

const addUserToProject = `-- name: AddUserToProject :one
INSERT INTO users_projects (user_id, project_id)
VALUES ($1, $2)
RETURNING user_id, project_id
`

type AddUserToProjectParams struct {
	UserID    string
	ProjectID string
}

func (q *Queries) AddUserToProject(ctx context.Context, arg AddUserToProjectParams) (UsersProject, error) {
	row := q.db.QueryRowContext(ctx, addUserToProject, arg.UserID, arg.ProjectID)
	var i UsersProject
	err := row.Scan(&i.UserID, &i.ProjectID)
	return i, err
}

const addUserToTask = `-- name: AddUserToTask :exec
INSERT INTO users_tasks (task_id, user_id)
VALUES ($1, $2)
ON CONFLICT (task_id, user_id) DO NOTHING
`

type AddUserToTaskParams struct {
	TaskID string
	UserID string
}

func (q *Queries) AddUserToTask(ctx context.Context, arg AddUserToTaskParams) error {
	_, err := q.db.ExecContext(ctx, addUserToTask, arg.TaskID, arg.UserID)
	return err
}

const createNewTaskStatus = `-- name: CreateNewTaskStatus :one
INSERT INTO task_status_types (owner_project_id, type)
VALUES ($1, $2)
RETURNING task_status_types_id, owner_project_id, type
`

type CreateNewTaskStatusParams struct {
	OwnerProjectID string
	Type           string
}

func (q *Queries) CreateNewTaskStatus(ctx context.Context, arg CreateNewTaskStatusParams) (TaskStatusType, error) {
	row := q.db.QueryRowContext(ctx, createNewTaskStatus, arg.OwnerProjectID, arg.Type)
	var i TaskStatusType
	err := row.Scan(&i.TaskStatusTypesID, &i.OwnerProjectID, &i.Type)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE project_id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, projectID)
	return err
}

const deleteProjectFromUsersProjects = `-- name: DeleteProjectFromUsersProjects :exec
DELETE FROM users_projects
WHERE project_id = $1
`

func (q *Queries) DeleteProjectFromUsersProjects(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectFromUsersProjects, projectID)
	return err
}

const deleteProjectsTask = `-- name: DeleteProjectsTask :exec
DELETE FROM project_tasks
WHERE project_id = $1
`

func (q *Queries) DeleteProjectsTask(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectsTask, projectID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE
FROM tasks
WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, taskID)
	return err
}

const getAllTaskStatuses = `-- name: GetAllTaskStatuses :many
SELECT task_status_types_id, owner_project_id, type
FROM task_status_types
`

func (q *Queries) GetAllTaskStatuses(ctx context.Context) ([]TaskStatusType, error) {
	rows, err := q.db.QueryContext(ctx, getAllTaskStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStatusType
	for rows.Next() {
		var i TaskStatusType
		if err := rows.Scan(&i.TaskStatusTypesID, &i.OwnerProjectID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT task_id, title, description, priority, user_id, created_at, deadline
FROM tasks
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.UserID,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT project_id, title, description, user_id, created_at FROM projects
WHERE project_id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, projectID string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, projectID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskById = `-- name: GetTaskById :one
SELECT task_id, title, description, priority, user_id, created_at, deadline
FROM tasks
WHERE task_id = $1
`

func (q *Queries) GetTaskById(ctx context.Context, taskID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskById, taskID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.UserID,
		&i.CreatedAt,
		&i.Deadline,
	)
	return i, err
}

const getTaskStatusByTaskId = `-- name: GetTaskStatusByTaskId :one
SELECT t.type
FROM task_statuses AS ts
         JOIN task_status_types AS t ON ts.task_status_id = t.task_status_types_id
WHERE ts.task_id = $1
`

func (q *Queries) GetTaskStatusByTaskId(ctx context.Context, taskID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskStatusByTaskId, taskID)
	var type_ string
	err := row.Scan(&type_)
	return type_, err
}

const getTasksByAuthor = `-- name: GetTasksByAuthor :many
SELECT task_id, title, description, priority, user_id, created_at, deadline
FROM tasks
WHERE user_id = $1
`

func (q *Queries) GetTasksByAuthor(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByAuthor, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.UserID,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByDeadline = `-- name: GetTasksByDeadline :many
SELECT task_id, title, description, priority, user_id, created_at, deadline
FROM tasks
WHERE deadline <= $1
`

func (q *Queries) GetTasksByDeadline(ctx context.Context, deadline sql.NullTime) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByDeadline, deadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.UserID,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByPriority = `-- name: GetTasksByPriority :many
SELECT task_id, title, description, priority, user_id, created_at, deadline
FROM tasks
WHERE priority = $1
`

func (q *Queries) GetTasksByPriority(ctx context.Context, priority string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByPriority, priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.UserID,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByProject = `-- name: GetTasksByProject :many
SELECT t.task_id, t.title, t.description, t.priority, t.user_id, t.created_at, t.deadline
FROM tasks AS t
         JOIN project_tasks AS pt ON t.task_id = pt.task_id
WHERE pt.project_id = $1
`

func (q *Queries) GetTasksByProject(ctx context.Context, projectID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.UserID,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByStatus = `-- name: GetTasksByStatus :many
SELECT t.task_id, t.title, t.description, t.priority, t.user_id, t.created_at, t.deadline
FROM tasks AS t
         JOIN task_statuses AS ts ON t.task_id = ts.task_id
         JOIN task_status_types AS tst ON ts.task_status_id = tst.task_status_types_id
WHERE tst.type = $1
`

func (q *Queries) GetTasksByStatus(ctx context.Context, type_ string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByStatus, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.UserID,
			&i.CreatedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProjects = `-- name: GetUserProjects :many
SELECT user_id, project_id FROM users_projects
WHERE user_id = $1
`

func (q *Queries) GetUserProjects(ctx context.Context, userID string) ([]UsersProject, error) {
	rows, err := q.db.QueryContext(ctx, getUserProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersProject
	for rows.Next() {
		var i UsersProject
		if err := rows.Scan(&i.UserID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTasks = `-- name: GetUserTasks :many
SELECT user_id, task_id FROM users_tasks
WHERE user_id = $1
`

func (q *Queries) GetUserTasks(ctx context.Context, userID string) ([]UsersTask, error) {
	rows, err := q.db.QueryContext(ctx, getUserTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersTask
	for rows.Next() {
		var i UsersTask
		if err := rows.Scan(&i.UserID, &i.TaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserInProject = `-- name: IsUserInProject :one
SELECT EXISTS (
    SELECT 1
    FROM users_projects
    WHERE project_id = $1 AND user_id = $2
)
`

type IsUserInProjectParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) IsUserInProject(ctx context.Context, arg IsUserInProjectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserInProject, arg.ProjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const newProject = `-- name: NewProject :one
INSERT INTO projects (title, description, user_id, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING project_id, title, description, user_id, created_at
`

type NewProjectParams struct {
	Title       string
	Description sql.NullString
	UserID      string
}

func (q *Queries) NewProject(ctx context.Context, arg NewProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, newProject, arg.Title, arg.Description, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const newTask = `-- name: NewTask :one
INSERT INTO tasks (title, description, priority, user_id, created_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING task_id, title, description, priority, user_id, created_at, deadline
`

type NewTaskParams struct {
	Title       string
	Description sql.NullString
	Priority    string
	UserID      string
}

func (q *Queries) NewTask(ctx context.Context, arg NewTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, newTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.UserID,
		&i.CreatedAt,
		&i.Deadline,
	)
	return i, err
}

const setTaskStatus = `-- name: SetTaskStatus :exec
UPDATE task_statuses ts
SET task_status_id = (SELECT tst.task_status_types_id
                      FROM task_status_types tst
                      WHERE tst.type = $2
                        AND tst.owner_project_id = (SELECT pt.project_id
                                                    FROM project_tasks pt
                                                    WHERE pt.task_id = $1))
WHERE ts.task_id = $1
`

type SetTaskStatusParams struct {
	TaskID string
	Type   string
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, setTaskStatus, arg.TaskID, arg.Type)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title = $1, description = $2
FROM users_projects
WHERE projects.project_id = users_projects.project_id AND users_projects.user_id = $3
RETURNING users_projects.user_id, users_projects.project_id, projects.project_id, title, description, projects.user_id, created_at
`

type UpdateProjectParams struct {
	Title       string
	Description sql.NullString
	UserID      string
}

type UpdateProjectRow struct {
	UserID      string
	ProjectID   string
	ProjectID_2 string
	Title       string
	Description sql.NullString
	UserID_2    string
	CreatedAt   sql.NullTime
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Title, arg.Description, arg.UserID)
	var i UpdateProjectRow
	err := row.Scan(
		&i.UserID,
		&i.ProjectID,
		&i.ProjectID_2,
		&i.Title,
		&i.Description,
		&i.UserID_2,
		&i.CreatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title       = $2,
    description = $3,
    priority    = $4,
    user_id     = $5
WHERE task_id = $1
RETURNING task_id, title, description, priority, user_id, created_at, deadline
`

type UpdateTaskParams struct {
	TaskID      string
	Title       string
	Description sql.NullString
	Priority    string
	UserID      string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.UserID,
		&i.CreatedAt,
		&i.Deadline,
	)
	return i, err
}

const userHasThisTask = `-- name: UserHasThisTask :one
SELECT COUNT(*) > 0 FROM users_tasks
WHERE user_id = $1 AND task_id = $2
`

type UserHasThisTaskParams struct {
	UserID string
	TaskID string
}

func (q *Queries) UserHasThisTask(ctx context.Context, arg UserHasThisTaskParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasThisTask, arg.UserID, arg.TaskID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
